### ISSUE TITLE
Messages with only HTML (and no plain text) content from Sendgrid are rejected

### ISSUE THREAD

**Issue by dwasyl** [yunojuno/django-inbound-email#28]
Hi there,

It's took me a bit of time to track down this problem with the package. In the `sendgrid.py` backend, text content is required, while HTML is optional:
`            text = _decode_POST_value(request, 'text')`
`            html = _decode_POST_value(request, 'html', default='')`

This means that any message with only HTML encoded text is rejected by the server. If `text` is changed to include a default, like this: 
`            text = _decode_POST_value(request, 'text', default='')`

Then any type of message can be received.

Not sure if it's easier for me to do a PR for this, or just make the quick change when you're doing other tests, but I'd be happy to. Not sure if this is an issue the other backends.

Cheers

**Comment by hugorodgerbrown** [comment]
Thanks @dwasyl - have picked this up on the latest edit. Will release once tests are done.

**Comment by dwasyl** [comment]
Fantastic! Thanks for the quick reply.

**Comment by hugorodgerbrown** [comment]
Released as 0.11.3
