### ISSUE TITLE
Imap / pop backend?

### ISSUE THREAD

**Issue by nanuxbe** [yunojuno/django-inbound-email#29]
Hi,

I'm looking for a solution similar to this project but compatible with IMAP/POP instead of request-based.

Would a PR with IMAP & POP backends + management command (to check the inbox periodically) be of interest to you for this project or would you rather not deal with "regular" e-mail checking.

Cheers

**Comment by hugorodgerbrown** [comment]
Hi @nanuxbe - that's an interesting one. Managing an inbox using POP/IMAP means managing state somewhere, and this is out of scope for this project. I think the way to do it (if you wanted to use this project) would be to have a separate project that did the polling and then post the results to this app for parsing (and create a new `PopRequestParser` backend). By which time you'd probably find it easier to just stick with the other project?

**Comment by vangale** [comment]
Hi @nanuxbe,

This might be what you are looking for: https://github.com/coddingtonbear/django-mailbox/

**Comment by nanuxbe** [comment]
@hugorodgerbrown Yes that's basically what I'm doing right now. No need to post though, calling the parser directly is enough. There is some common code between the new project and django-inbound-email, that's why I'm asking but it is indeed very little amount of common code and can live in a separate project.

@vangale Thanks for the pointer unfortunately I already took a look at that project and it is very much coupled with creating db records for each mail which I don't want to do.

**Comment by hugorodgerbrown** [comment]
Not that this will help right now, but we have a companion app that we haven't yet OSS'd that handles the auditing of messages in/out of our platform (email, sms, push notification), hence not having any models in this app - they are in the other one.
